#!/bin/sh

CXX=g++
command -v clang 2>&1 > /dev/null && CXX=clang++
echo "Building with CXX=$CXX"
sleep 1
[ -d m4 ] || mkdir m4
autoreconf -i && ./configure --enable-silent-rules CXX=$CXX     \
        && make
if [ "$?" = "0" ]
then
	make check || (cat test-suite.log && exit 1)
else
	exit 1
fi

