#!/bin/sh

CXX=g++
command -v clang 2>&1 > /dev/null && CXX=clang++
echo "Building with CXX=$CXX"
sleep 1
[ -d m4 ] || mkdir m4
autoreconf -i && ./configure --enable-silent-rules CXX=$CXX     \
        && make && make test

